Algoritmo "Exemplo 3"

Var

   quantidade, i, numero, soma : inteiro

Inicio

      escreva ("Quantos números serão digitados? ")
      leia (quantidade)
      
      soma <- 0
      
      para i de 1 ate quantidade faca

           escreva ("Digite um número: ")
           leia (numero)
           
           soma <- soma + numero

      fimpara
      
      escreval
      escreval ("A soma é = ", soma)


Fimalgoritmo