Algoritmo "Exercício - Dentro fora"

Var

   n, x, i, dentro, fora : inteiro

Inicio

      escreva ("Quantos números você vai digitar? ")
      leia(n)
      escreval
      
      dentro <- 0
      fora <- 0
      
      para i de 1 ate n faca
      
           escreva("Digite um número: ")
           leia(x)
           
           se (x >= 10) e (x <= 20) entao
              dentro <- dentro + 1
           senao
              fora <- fora + 1
           fimse
           
      fimpara
      
      escreval
      escreval(dentro, " dentro")
      escreval(fora, " fora")

Fimalgoritmo